---
# Create a StorageClass for EBS volumes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "true"
---
# Create a PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
  namespace: retail-store
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 5Gi
---
# Create a MySQL deployment using the PVC
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: retail-store
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: retaildb
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-data-pvc
---
# Create a Service for MySQL
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: retail-store
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
# Create a simple app to demonstrate data persistence
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-writer
  namespace: retail-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-writer
  template:
    metadata:
      labels:
        app: data-writer
    spec:
      containers:
      - name: data-writer
        image: mysql:8.0
        command: ["/bin/bash"]
        args:
        - "-c"
        - "while true; do echo $(date) >> /data/timestamp.txt; sleep 30; done"
        volumeMounts:
        - name: shared-data
          mountPath: /data
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
  namespace: retail-store
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi